server:
  port: 8081


stats-server:
  url: "http://stats-server:9090"

ewm-service:
  url: "http://ewm-service:8081"


spring:
  application:
    name: stats-server
  main:
    banner-mode: off

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: "dbuser"
    password: "12345"
    url: "jdbc:postgresql://ewm-db:5432/ewmdb"
    driver-class-name: org.postgresql.Driver

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"