CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250)        NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000) NOT NULL,
    category_id        BIGINT        NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    event_date         TIMESTAMP     NOT NULL,
    lat                DECIMAL(8, 6) CHECK (lat >= -90 AND lat <= 90),
    lon                DECIMAL(9, 6) CHECK (lon >= -180 AND lon <= 180),
    paid               BOOLEAN       NOT NULL DEFAULT FALSE,
    participant_limit  INTEGER                DEFAULT 0,
    request_moderation BOOLEAN       NOT NULL DEFAULT TRUE,
    title              VARCHAR(120)  NOT NULL,
    initiator_id       BIGINT        NOT NULL,
    created_on         TIMESTAMP              DEFAULT CURRENT_TIMESTAMP,
    published_on       TIMESTAMP,
    state              VARCHAR(20)            DEFAULT 'PENDING',
    confirmed_requests INTEGER                DEFAULT 0,
    views              BIGINT                 DEFAULT 0,
    comments_disabled  BOOLEAN       NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_events_initiator FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT NOT NULL,
    created      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    requester_id BIGINT NOT NULL,
    status       VARCHAR   DEFAULT 'PENDING',

    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_requester_id FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN     NOT NULL DEFAULT false,
    title  VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,

    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_events_compilation FOREIGN KEY (compilation_id)
        REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_events_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);


CREATE TABLE comments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text              TEXT   NOT NULL,
    user_id           BIGINT NOT NULL,
    event_id          BIGINT NOT NULL,
    parent_comment_id BIGINT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT NULL,
    edited            BOOLEAN   DEFAULT FALSE,
    deleted           BOOLEAN   DEFAULT FALSE,

    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (parent_comment_id) REFERENCES comments (id),
);

-- users
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- categories
CREATE INDEX IF NOT EXISTS idx_categories_name ON categories (name);

-- events
CREATE INDEX IF NOT EXISTS idx_events_category ON events (category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator ON events (initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON events (state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_events_published ON events (published_on);

-- requests
CREATE INDEX IF NOT EXISTS idx_requests_event ON requests (event_id);
CREATE INDEX IF NOT EXISTS idx_requests_requester ON requests (requester_id);
CREATE INDEX IF NOT EXISTS idx_requests_status ON requests (status);

-- compilations
CREATE INDEX IF NOT EXISTS idx_compilations_pinned ON compilations (pinned);
CREATE INDEX IF NOT EXISTS idx_compilations_title ON compilations (title);

-- compilation_events
CREATE INDEX IF NOT EXISTS idx_compilation_events_compilation ON compilation_events (compilation_id);
CREATE INDEX IF NOT EXISTS idx_compilation_events_event ON compilation_events (event_id);

-- comments
CREATE INDEX IF NOT EXISTS idx_comments_user ON comments (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_event ON comments (event_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent ON comments (parent_comment_id);
CREATE INDEX IF NOT EXISTS idx_comments_created ON comments (created_at);
CREATE INDEX IF NOT EXISTS idx_comments_event_created ON comments (event_id, created_at);